# Getting familiar with NumPy array usage:
>Select the i2dl env in conda (which has almost everything)

>Import NumPy first before started

In [1]:
import numpy as np

## 1. Create an array with 36 elements

In [2]:
# arr0 = np.array([1.1, 2.1, 3.1, 4.1],[5.1, 6.1, 7.1, 8.1],[9.1, 10.1, 11.1, 12.1],[13.1, 14.1, 15.1, 16.1],[17.1, 18.1, 19.1, 20.1],[21.1, 22.1, 23.1, 24.1],[25.1, 26.1, 27.1, 28.1],[29.1, 30.1, 31.1, 32.1],[33.1, 34.1, 35.1, 36.1])
# the above is not correct TypeError: array() takes from 1 to 2 positional arguments but 9 were given, missing square brackets "[]"
arr0 = np.array([[1.1, 2.1, 3.1, 4.1],[5.1, 6.1, 7.1, 8.1],[9.1, 10.1, 11.1, 12.1],[13.1, 14.1, 15.1, 16.1],[17.1, 18.1, 19.1, 20.1],[21.1, 22.1, 23.1, 24.1],[25.1, 26.1, 27.1, 28.1],[29.1, 30.1, 31.1, 32.1],[33.1, 34.1, 35.1, 36.1]])
print("arr0:\n", arr0)
print("arr0 shape:\n", arr0.shape)
print("arr0 data type:\n", arr0.dtype)

arr0:
 [[ 1.1  2.1  3.1  4.1]
 [ 5.1  6.1  7.1  8.1]
 [ 9.1 10.1 11.1 12.1]
 [13.1 14.1 15.1 16.1]
 [17.1 18.1 19.1 20.1]
 [21.1 22.1 23.1 24.1]
 [25.1 26.1 27.1 28.1]
 [29.1 30.1 31.1 32.1]
 [33.1 34.1 35.1 36.1]]
arr0 shape:
 (9, 4)
arr0 data type:
 float64


## 2. Convert data type to int

In [3]:
print("\n=======convert data type to int=======\n")
arr0 = arr0.astype(int)
print("arr0:\n", arr0)
print("arr0 datatype:\n", arr0.dtype)


=======convert data type to int=======

arr0:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]
arr0 datatype:
 int32


## 3. Reshape the array

### 3.1 Reshape arr0:

In [4]:
# reshape to 6x6
print("1. reshape to 6x6:\n")
arr0 = arr0.reshape(6,6)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


1. reshape to 6x6:

arr0:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
arr0 shape: (6, 6)


In [5]:
# reshape to 3x12 using -1
print("\n2. reshape to 3x12 using -1:   #.reshape(3, -1) or. reshape(-1, 12)\n")
arr0 = arr0.reshape(3,-1)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


2. reshape to 3x12 using -1:   #.reshape(3, -1) or. reshape(-1, 12)

arr0:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
arr0 shape: (3, 12)


In [6]:
# reshape to 4x9 using -1
print("\n3. reshape to 4x9 using -1:    #.reshape(4, -1) or. reshape(-1, 9)\n")
arr0 = arr0.reshape(4,-1)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


3. reshape to 4x9 using -1:    #.reshape(4, -1) or. reshape(-1, 9)

arr0:
 [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]
arr0 shape: (4, 9)


In [7]:
# reshape back to 6x6
print("\n4. reshape back to 6x6:\n")
arr0 = arr0.reshape(6,6)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


4. reshape back to 6x6:

arr0:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
arr0 shape: (6, 6)


In [8]:
# reshape to row vector using -1
print("\n4. reshape to row vector using -1: # using .reshape(1, -1)\n")
arr0 = arr0.reshape(1,-1)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


4. reshape to row vector using -1: # using .reshape(1, -1)

arr0:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36]]
arr0 shape: (1, 36)


In [9]:
# reshape to column vector using -1
print("\n5. reshape to column vector using -1:  # using .reshape(-1, 1)\n")
arr0 = arr0.reshape(-1,1)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


5. reshape to column vector using -1:  # using .reshape(-1, 1)

arr0:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]]
arr0 shape: (36, 1)


In [10]:
# reshape back to 6x6
print("\n6. reshape back to 6x6:\n")
arr0 = arr0.reshape(6,6)
print("arr0:\n", arr0)
print("arr0 shape:", arr0.shape)


6. reshape back to 6x6:

arr0:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
arr0 shape: (6, 6)


In [11]:
# using flatten to reshape to 1D array
print("\n7. using flatten to reshape to 1D array:\n")
arr_flat = arr0.flatten()
print("arr_flat:", arr_flat)
print("arr_flat shape:", arr_flat.shape)


7. using flatten to reshape to 1D array:

arr_flat: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
arr_flat shape: (36,)


In [12]:
# using ravel to reshape to 1D array
print("\n8. using ravel to reshape to 1D array:\n")
arr_ravel = arr0.ravel()
print("arr_ravel:", arr_ravel)
print("arr_ravel shape:", arr_ravel.shape)


8. using ravel to reshape to 1D array:

arr_ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
arr_ravel shape: (36,)


In [13]:
# changing original array and checking the effect on flatten and ravel
print("\n9. changing original array and checking the effect on flatten and ravel:\n")
# arr0 = arr0.reshape(-1,1), this won't make effects. because values are not changed
arr0[0,0] = 100
print("arr[0,0] changed to 100\n")
print("arr_flat:\n", arr_flat) # just a copy of original array
print("arr_ravel:\n", arr_ravel) # something like reference in C++, so it will change


9. changing original array and checking the effect on flatten and ravel:

arr[0,0] changed to 100

arr_flat:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
arr_ravel:
 [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36]


### 3.2 Splitting or concatenating the array 

#### 3.2.1 Split the array into 3 equal parts


(a) Split the array into 3 equal parts

In [14]:
print("\narr0:\n", arr0, "shape: ", arr0.shape)
arr_split = np.split(arr0, 3)
print("\narr_split:\n", arr_split)


arr0:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]] shape:  (6, 6)

arr_split:
 [array([[100,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])]


(b) But What exactly is arr_split?     (Do not use np.dtype(), use type(...)instead)

In [15]:
print("arr_split date type:\n", type(arr_split), "\n")

arr_split date type:
 <class 'list'> 



(c) Get the element in the arr_split list.

In [16]:
print("\narr_split[0]:\n", arr_split[0], "shape:", arr_split[0].shape)
print("\narr_split[1]:\n", arr_split[1], "shape:", arr_split[1].shape)
print("\narr_split[2]:\n", arr_split[2], "shape:", arr_split[2].shape)



arr_split[0]:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]] shape: (2, 6)

arr_split[1]:
 [[13 14 15 16 17 18]
 [19 20 21 22 23 24]] shape: (2, 6)

arr_split[2]:
 [[25 26 27 28 29 30]
 [31 32 33 34 35 36]] shape: (2, 6)


#### 3.2.2 Concatenate the array in different directions

>The method is ```np.concatenate()```

(a) Concatenate along rows: 
- ``np.concatenate((array1,array2,...),(axis=0))``

In [17]:
add_0 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print("The array to be concatenated:\n", arr_split[0], "shape:", arr_split[0].shape)
print("Add_0\n",add_0,"shape:",add_0.shape)
con_0 = np.concatenate((arr_split[0], add_0), axis=0)
print("\nConcatenate arr_split[0] along rows(axis=0):\n", con_0, "shape:", con_0.shape)

The array to be concatenated:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]] shape: (2, 6)
Add_0
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] shape: (3, 6)

Concatenate arr_split[0] along rows(axis=0):
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]] shape: (5, 6)


(b) Concatenate along column:
- `np.concatenate((array1,array2,...),(axis=1))`

In [18]:
add_1 = np.array([[1,2,3,4],[5,6,7,8]])
print("the array to be concatenated:\n", arr_split[0])
print("add_1\n",add_1,"shape:",add_1.shape)
# concatenate along columns
con_1=np.concatenate((arr_split[0], add_1), axis=1)
print("\n(1) concatenate arr_split[0] along columns(axis=1):\n",con_1, "shape:", con_1.shape)

the array to be concatenated:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]
add_1
 [[1 2 3 4]
 [5 6 7 8]] shape: (2, 4)

(1) concatenate arr_split[0] along columns(axis=1):
 [[100   2   3   4   5   6   1   2   3   4]
 [  7   8   9  10  11  12   5   6   7   8]] shape: (2, 10)


## 4.Indexing and Slicing arrays
- Indexing syntax: `arr[[::],[::]]`
- Slicing syntax `[start:stop:step]`
### 4.1 Indexing
- Indexing using `arr[i,j]`

In [19]:
# check up the arr0
print("\narr0:\n", arr0, "shape:", arr0.shape)
# arr0(1,2) not possible because () indexing not possible for numpy array
# print the element on the 2nd row and 3rd column
print("\nThe element on the 2nd row and 3rd column indexed by arr0[1,2]: ", arr0[1,2])


arr0:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]] shape: (6, 6)

The element on the 2nd row and 3rd column indexed by arr0[1,2]:  9


- Indexing using `arr[i_0:i_1,j_0:j_1]` or `arr([i_0:i_1,j_0:j_1])`

In [20]:
# check up the arr0
print("\narr0:\n", arr0, "shape:", arr0.shape)

# print the 2D array at row from 1 to 3 and column from 2 to 4
print("\n2D array at row from 1 to 3(included)\nand column from 2 to 4(included):\n", arr0[0:3,1:4])
print("Indexed by arr0[0:3,1:4]:\n")


arr0:
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]
 [ 31  32  33  34  35  36]] shape: (6, 6)

2D array at row from 1 to 3(included)
and column from 2 to 4(included):
 [[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]
Indexed by arr0[0:3,1:4]:



* <small>But how then? \
Why indexing "from" 1st row the index is `1-1=0`, while intending to include the range till 3rd row "included"--- the index is not `3-1=2`?\
Well it is about the "slicing" rule in python.\
Let us move on to the next section.</small> 

### 4.2 Slicing
- Slicing using `[start:end]`

In [21]:
# let's first flatten the array arr0 to make it more intuitive
arr0_flat = arr0.flatten()
# check up the arr0_flat
print("\narr0_flat:\n", arr0_flat, "shape:", arr0_flat.shape)

# print the 1D array from 2nd to 5th element
print("\n1D array from 2nd to 5th element:\n", arr0_flat[1:5])
print("Indexed by arr0_flat[1:5]:\n")
print("This is because the end element will not be included in the indexing, so index for 5th element is 5-1+1=0")


arr0_flat:
 [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36] shape: (36,)

1D array from 2nd to 5th element:
 [2 3 4 5]
Indexed by arr0_flat[1:5]:

This is because the end element will not be included in the indexing, so index for 5th element is 5-1+1=0


- Slicing using `[start:end:step]` where `step>0` 

In [22]:
# check up the arr0_flat
print("\narr0_flat:\n", arr0_flat, "shape:", arr0_flat.shape)

# get the value from 2 to 10, step 2
print("\nValue from 2 to 10, step 2:\n", arr0_flat[1:10:2])
print("Indexed by arr0_flat[1:10:2]:\n")

# print what is indexed by arr0_flat[10:1:2]
print("\nValue from 10 to 1, step 2:\n", arr0_flat[10:1:2])
print("Indexed by arr0_flat[10:1:2]:\n")
print("This is because the start index is greater than the end index, \
      \nbut the step 2 is positive, so stepping forward returns empty array")


arr0_flat:
 [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36] shape: (36,)

Value from 2 to 10, step 2:
 [ 2  4  6  8 10]
Indexed by arr0_flat[1:10:2]:


Value from 10 to 1, step 2:
 []
Indexed by arr0_flat[10:1:2]:

This is because the start index is greater than the end index,       
but the step 2 is positive, so stepping forward returns empty array


- Slicing using `[start:end:step]` where `step<0` 
    - Common usage:`[::-1]`

In [23]:
# check up the arr0_flat
print("\narr0_flat:\n", arr0_flat, "shape:", arr0_flat.shape)
# print the reversed array
print("\nReversed array:\n", arr0_flat[::-1], "Indexed by arr0_flat[::-1]:\n")

# print the reversed array from 20 to 8(included), step -2
print("\nReversed array from 20 to 8(included), step -2:\n", arr0_flat[19:6:-2], "Indexed by arr0_flat[19:6:-2]:\n")
print("The eighth element is index by 7, \nbut the end element won't be reached by indexing it, so the end index is 7-1=6")


arr0_flat:
 [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36] shape: (36,)

Reversed array:
 [ 36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21  20  19
  18  17  16  15  14  13  12  11  10   9   8   7   6   5   4   3   2 100] Indexed by arr0_flat[::-1]:


Reversed array from 20 to 8(included), step -2:
 [20 18 16 14 12 10  8] Indexed by arr0_flat[19:6:-2]:

The eighth element is index by 7, 
but the end element won't be reached by indexing it, so the end index is 7-1=6


### 4.3 Combined Indexing and Slicing

In [24]:
# reinitialize the arr0 to 10x10
arr0 = np.arange(100).reshape(10,10)

# check the arr0
print("\narr0:\n", arr0, "shape:", arr0.shape)

# print the 2D array from 2nd row to 7th row and 3rd column to 10th column
print("\n2D array from 2nd row to 7th row and 3rd column to 10th column:\n",\
    arr0[1:7,2:10], "Indexed by arr0[1:7,2:10]:\n")

# print the 2D array from 2nd row to 7th row and 3rd column to 10th column, step 3 at row, and step 2 at column
print("\n2D array from 2nd row to 7th row and 3rd column to 10th column, step 3 at row, and step 2 at column:\n",\
    arr0[1:7:3,2:10:2], "Indexed by arr0[1:7:3,2:10:2]:\n")




arr0:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] shape: (10, 10)

2D array from 2nd row to 7th row and 3rd column to 10th column:
 [[12 13 14 15 16 17 18 19]
 [22 23 24 25 26 27 28 29]
 [32 33 34 35 36 37 38 39]
 [42 43 44 45 46 47 48 49]
 [52 53 54 55 56 57 58 59]
 [62 63 64 65 66 67 68 69]] Indexed by arr0[1:7,2:10]:


2D array from 2nd row to 7th row and 3rd column to 10th column, step 3 at row, and step 2 at column:
 [[12 14 16 18]
 [42 44 46 48]] Indexed by arr0[1:7:3,2:10:2]:



In [25]:
# print the 2D array from 2nd row to 7th row and 3rd column to 10th column
print("\n2D array from 2nd row to 7th row and 3rd column to 10th column:\n",\
    arr0[1:7,2:10], "Indexed by arr0[1:7,2:10]:\n")

# print the 2D array from 7th row to 2th row and 10rd column to 3th column
print("\n2D array from 7th row to 2nd row and 10th column to 3rd column(reverse):\n",\
    arr0[6:0:-1,9:1:-1], "Indexed by arr0[6:1:-1,9:2:-1]:\n")

# print the 2D array from 7th row to 2th row and 10rd column to 3th column, step -3 at row, and step -2 at column
print("\n2D array from 7th row to 2nd row and 10th column to 3rd column, step -3 at row, and step -2 at column:\n",\
    arr0[6:0:-3,9:1:-2], "Indexed by arr0[6:1:-3,9:2:-2]:\n")


2D array from 2nd row to 7th row and 3rd column to 10th column:
 [[12 13 14 15 16 17 18 19]
 [22 23 24 25 26 27 28 29]
 [32 33 34 35 36 37 38 39]
 [42 43 44 45 46 47 48 49]
 [52 53 54 55 56 57 58 59]
 [62 63 64 65 66 67 68 69]] Indexed by arr0[1:7,2:10]:


2D array from 7th row to 2nd row and 10th column to 3rd column(reverse):
 [[69 68 67 66 65 64 63 62]
 [59 58 57 56 55 54 53 52]
 [49 48 47 46 45 44 43 42]
 [39 38 37 36 35 34 33 32]
 [29 28 27 26 25 24 23 22]
 [19 18 17 16 15 14 13 12]] Indexed by arr0[6:1:-1,9:2:-1]:


2D array from 7th row to 2nd row and 10th column to 3rd column, step -3 at row, and step -2 at column:
 [[69 67 65 63]
 [39 37 35 33]] Indexed by arr0[6:1:-3,9:2:-2]:

