# Array Math

In [1]:
import numpy as np

## 1. Basics
### 1.1 Manipulation on elements
#### 1.1.1 Modification at some certain location

In [2]:
# Initialize an array(matrices)
A = np.arange(15).reshape(3, 5)
print("the array is A = np.arange(15).\
    reshape(3, 5): \n", A, "shape: ", A.shape)

# Modify the array at row i and column j
A[1, 3] = 100
print("\nthe modified array at [1,3] is 100: \n", A, "shape: ", A.shape)

# Modify the array at row i
A[1, :] = ([1, 2, 3, 4, 5])
print("\nthe modified array at row 1 is [1,2,3,4,5]: \n", A, "shape: ", A.shape)

# Modify at region [i:k, j:l]
A[1:3, 2:5] = 0
print("\nthe modified array at region [1:3, 2:5] is 0: \n", A, "shape: ", A.shape)


the array is A = np.arange(15).    reshape(3, 5): 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] shape:  (3, 5)

the modified array at [1,3] is 100: 
 [[  0   1   2   3   4]
 [  5   6   7 100   9]
 [ 10  11  12  13  14]] shape:  (3, 5)

the modified array at row 1 is [1,2,3,4,5]: 
 [[ 0  1  2  3  4]
 [ 1  2  3  4  5]
 [10 11 12 13 14]] shape:  (3, 5)

the modified array at region [1:3, 2:5] is 0: 
 [[ 0  1  2  3  4]
 [ 1  2  0  0  0]
 [10 11  0  0  0]] shape:  (3, 5)


#### 1.1.2 Add or Substract

In [3]:
print("A: \n", A)
# Add 1 to each element of the array
A = A + 1
print("\nA = A + 1: \n", A)
A = np.add(A, 1)
print("\nA = np.add(A, 1): \n", A)
print("A+1 is equivalent to np.add(A, 1)")

# Subtract 1 from each element of the array
A = A - 1
print("\nA = A - 1: \n", A)
A = np.subtract(A, 1)
print("\nA = np.subtract(A, 1): \n", A)
print("A-1 is equivalent to np.subtract(A, 1)")

A: 
 [[ 0  1  2  3  4]
 [ 1  2  0  0  0]
 [10 11  0  0  0]]

A = A + 1: 
 [[ 1  2  3  4  5]
 [ 2  3  1  1  1]
 [11 12  1  1  1]]

A = np.add(A, 1): 
 [[ 2  3  4  5  6]
 [ 3  4  2  2  2]
 [12 13  2  2  2]]
A+1 is equivalent to np.add(A, 1)

A = A - 1: 
 [[ 1  2  3  4  5]
 [ 2  3  1  1  1]
 [11 12  1  1  1]]

A = np.subtract(A, 1): 
 [[ 0  1  2  3  4]
 [ 1  2  0  0  0]
 [10 11  0  0  0]]
A-1 is equivalent to np.subtract(A, 1)


#### 1.1.3 Multiply, Divide, Power and Square-root

In [4]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("\nA: \n", A)
# Multiply each element of the array by 2
A = A * 2
print("\nA = A * 2: \n", A)
A = (np.multiply(A, 2)).astype(int)
print("\nA = np.multiply(A, 2): \n", A)
print("A*2 is equivalent to np.multiply(A, 2)")

# Divide each element of the array by 2
A = A / 2
print("\nA = A / 2: \n", A)
A = (np.divide(A, 2))
print("\nA = np.divide(A, 2): \n", A)
print("A/2 is equivalent to np.divide(A, 2)")


A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

A = A * 2: 
 [[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]

A = np.multiply(A, 2): 
 [[ 0  4  8 12 16]
 [20 24 28 32 36]
 [40 44 48 52 56]]
A*2 is equivalent to np.multiply(A, 2)

A = A / 2: 
 [[ 0.  2.  4.  6.  8.]
 [10. 12. 14. 16. 18.]
 [20. 22. 24. 26. 28.]]

A = np.divide(A, 2): 
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
A/2 is equivalent to np.divide(A, 2)


#### 1.1.4 Power and Square-root

In [5]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Power each element of the array by 2
A = A ** 2
print("\nA = A ** 2: \n", A)
A = np.power(A, 2).astype(int)
print("\nA = np.power(A, 2).astype(int): \n", A)
print("A**2 is equivalent to np.power(A, 2)")

# Square root of each element of the array
A = A ** 0.5
print("\nA = A ** 0.5: \n", A)
A = np.sqrt(A)
print("\nA = np.sqrt(A): \n", A)
print("A**0.5 is equivalent to np.sqrt(A)")

A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

A = A ** 2: 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]

A = np.power(A, 2).astype(int): 
 [[    0     1    16    81   256]
 [  625  1296  2401  4096  6561]
 [10000 14641 20736 28561 38416]]
A**2 is equivalent to np.power(A, 2)

A = A ** 0.5: 
 [[  0.   1.   4.   9.  16.]
 [ 25.  36.  49.  64.  81.]
 [100. 121. 144. 169. 196.]]

A = np.sqrt(A): 
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
A**0.5 is equivalent to np.sqrt(A)


#### 1.1.5 Floor, Ceil and Round

In [6]:
# Reinitalize the array randomly with float numbers 3x5
A = np.random.rand(3, 5)
print("\nA: \n", A)

# Round each element of the array
print("\nA = np.round(A): \n", np.round(A))
# Ceil each element of the array
print("\nA = np.ceil(A): \n", np.ceil(A))
# Floor each element of the array
print("\nA = np.floor(A): \n", np.floor(A))



A: 
 [[0.82060563 0.95205604 0.70804795 0.27019154 0.86925324]
 [0.50085383 0.47686858 0.6538168  0.48234532 0.82297247]
 [0.29978751 0.99810856 0.83644711 0.57411158 0.05527486]]

A = np.round(A): 
 [[1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 0.]]

A = np.ceil(A): 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

A = np.floor(A): 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


- Special

In [7]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Absolute value of each element of the array
print("\nA = np.abs(A): \n", np.abs(A))
# Sine of each element of the array
print("\nA = np.sin(A):\n(cos and tan is als\
      o available) \n", np.sin(A))
# Exponential of each element of the array
print("\nA = np.exp(A): \n", np.exp(A))
# Natural logarithm of each element of the array
print("\nA = np.log(A): \n", np.log(A))

A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

A = np.abs(A): 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

A = np.sin(A):
(cos and tan is als      o available) 
 [[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]]

A = np.exp(A): 
 [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
  1.20260428e+06]]

A = np.log(A): 
 [[      -inf 0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936 2.63905733]]


C:\Users\24707\AppData\Local\Temp\ipykernel_26028\1749042973.py:12: RuntimeWarning: divide by zero encountered in log
  print("\nA = np.log(A): \n", np.log(A))


### 1.2 Statistics on Array
#### 1.2.1 Mean and Sum

In [8]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Sum of all elements of the array
print("\nnp.sum(A): \n", np.sum(A))
# Sum of all elements of the array along the column
print("\nnp.sum(A, axis=0): \n", np.sum(A, axis=0))

# Mean of all elements of the array
print("\nnp.mean(A): \n", np.mean(A))
# Mean of all elements of the array along the row
print("\nnp.mean(A, axis=1): \n", np.mean(A, axis=1))

A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

np.sum(A): 
 105

np.sum(A, axis=0): 
 [15 18 21 24 27]

np.mean(A): 
 7.0

np.mean(A, axis=1): 
 [ 2.  7. 12.]


#### 1.2.2 Sorting

In [9]:
# Reinitalize the array
A = np.random.randint(20, size=(3, 5))
print("A: \n", A)

# Sort the array
print("\nnp.sort(A): \n", np.sort(A))
print("\nnp.sort(A, axis=1): \n", np.sort(A, axis=1))
print("\nthe default is sorting the last axis\n\
    , which is axis=1. It sorts column while row does not change")

# While in C++ we can std::sort with a functor, but python does not support it

A: 
 [[10 16 15 12 17]
 [ 3  1 11  6 18]
 [11  1  9 18  7]]

np.sort(A): 
 [[10 12 15 16 17]
 [ 1  3  6 11 18]
 [ 1  7  9 11 18]]

np.sort(A, axis=1): 
 [[10 12 15 16 17]
 [ 1  3  6 11 18]
 [ 1  7  9 11 18]]

the default is sorting the last axis
    , which is axis=1. It sorts column while row does not change


#### 1.2.3 Min and Max

In [10]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)

# Minimum of all elements of the array
print("\nnp.min(A): \n", np.min(A))
# Minimum of all elements of the array along the row
print("\nnp.min(A, axis=1): \n", np.min(A, axis=1))

# Maximum of all elements of the array
print("\nnp.max(A): \n", np.max(A))
# Maximum of all elements of the array along the column
print("\nnp.max(A, axis=0): \n", np.max(A, axis=0))

A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

np.min(A): 
 0

np.min(A, axis=1): 
 [ 0  5 10]

np.max(A): 
 14

np.max(A, axis=0): 
 [10 11 12 13 14]


#### 1.2.4 Variance, Covariance, Standard Deviation

In [11]:
# Reinitalize the array
A = (np.random.rand(3,5)*100).astype(int)
print("A: \n", A)

# Variance of all elements of the array
print("\nnp.var(A): \n", np.var(A))
# Variance of all elements of the array along the row
print("\nnp.var(A, axis=1): \n", np.var(A, axis=1))

# Standard deviation of all elements of the array
print("\nnp.std(A): \n", np.std(A))
# Standard deviation of all elements of the array along the column
print("\nnp.std(A, axis=0): \n", np.std(A, axis=0))

# Correlation coefficient of all elements of the array
print("\nnp.corrcoef(A): \n", np.corrcoef(A))


A: 
 [[60 65 40 76 55]
 [58 54 85 20 86]
 [20 47 37 47 85]]

np.var(A): 
 430.48888888888894

np.var(A, axis=1): 
 [140.56 587.84 454.56]

np.std(A): 
 20.748226162467212

np.std(A, axis=0): 
 [18.40289832  7.40870359 21.9544984  22.86676385 14.38363267]

np.corrcoef(A): 
 [[ 1.         -0.90283917  0.0085453 ]
 [-0.90283917  1.          0.30619695]
 [ 0.0085453   0.30619695  1.        ]]


## 2. Linear Algebra
### 2.1 Elementwise manipulations
#### 2.1.1 Addition and Subatraction

In [12]:
# Initialize two arrays (matrices)
A = np.random.randint(10, size=(3, 5))
B = np.random.randint(10, size=(3, 5))

print("A: \n", A, "\nB: \n", B)

# Element-wise addition of two arrays
print("\nA + B: \n", A + B)
print("\nIs it' equivalent to 'np.add(A, B)'? \n", \
    np.array_equal(A + B, np.add(A, B)),\
        "----Returned by 'np.array_equal(A + B, np.add(A, B))'")

# Element-wise subtraction of two arrays
print("\nA - B: \n", A - B)
print("\nIs it equivalent to 'np.subtract(A, B)'? \n", \
    np.array_equal(A - B, np.subtract(A, B)),\
        "----Returned by 'np.array_equal(A - B, np.subtract(A, B))'")


A: 
 [[2 6 8 2 8]
 [3 7 3 4 5]
 [2 6 7 8 2]] 
B: 
 [[1 7 3 9 2]
 [1 8 5 5 9]
 [4 9 3 8 1]]

A + B: 
 [[ 3 13 11 11 10]
 [ 4 15  8  9 14]
 [ 6 15 10 16  3]]

Is it' equivalent to 'np.add(A, B)'? 
 True ----Returned by 'np.array_equal(A + B, np.add(A, B))'

A - B: 
 [[ 1 -1  5 -7  6]
 [ 2 -1 -2 -1 -4]
 [-2 -3  4  0  1]]

Is it equivalent to 'np.subtract(A, B)'? 
 True ----Returned by 'np.array_equal(A - B, np.subtract(A, B))'


#### 2.1.2 Multiplication and Division

In [13]:
# Reinitialize two arrays (matrices)
A = np.random.randint(10, size=(3, 5))
B = np.random.randint(10, size=(3, 5))

print("A: \n", A, "\nB: \n", B)

# Elementwise multiplication of two arrays
print("\nA * B: \n", A * B)
print("\nIs it equivalent to 'np.multiply(A, B)'? \n", \
    np.array_equal(A * B, np.multiply(A, B)),\
        "----Returned by 'np.array_equal(A * B, np.multiply(A, B))'")

# Elementwise division of two arrays
print("\nA / B: \n", A / B)
print("\nIs it equivalent to 'np.divide(A, B)'? \n", \
    np.array_equal(A / B, np.divide(A, B)),\
        "----Returned by 'np.array_equal(A / B, np.divide(A, B))'")

A: 
 [[8 9 7 4 2]
 [4 5 7 1 3]
 [8 0 0 1 5]] 
B: 
 [[6 0 3 5 4]
 [8 7 1 7 4]
 [7 5 5 5 1]]

A * B: 
 [[48  0 21 20  8]
 [32 35  7  7 12]
 [56  0  0  5  5]]

Is it equivalent to 'np.multiply(A, B)'? 
 True ----Returned by 'np.array_equal(A * B, np.multiply(A, B))'

A / B: 
 [[1.33333333        inf 2.33333333 0.8        0.5       ]
 [0.5        0.71428571 7.         0.14285714 0.75      ]
 [1.14285714 0.         0.         0.2        5.        ]]

Is it equivalent to 'np.divide(A, B)'? 
 True ----Returned by 'np.array_equal(A / B, np.divide(A, B))'


C:\Users\24707\AppData\Local\Temp\ipykernel_26028\3736590940.py:14: RuntimeWarning: divide by zero encountered in divide
  print("\nA / B: \n", A / B)
C:\Users\24707\AppData\Local\Temp\ipykernel_26028\3736590940.py:16: RuntimeWarning: divide by zero encountered in divide
  np.array_equal(A / B, np.divide(A, B)),\


#### 2.1.3 Elementwise Power

In [14]:
# Reinitialize two arrays (matrices)
A = np.random.randint(4, size=(3, 5))
B = np.random.randint(4, size=(3, 5))

print("A: \n", A, "\nB: \n", B)

# Elementwise power of two arrays
print("\nA ** B: \n", A ** B)
print("\nIs it equivalent to 'np.power(A, B)'? \n", \
    np.array_equal(A ** B, np.power(A, B)),\
        "----Returned by 'np.array_equal(A ** B, np.power(A, B))'")

A: 
 [[1 1 1 3 1]
 [1 0 3 1 3]
 [2 3 0 1 3]] 
B: 
 [[0 2 2 0 0]
 [3 0 3 0 2]
 [3 1 2 1 1]]

A ** B: 
 [[ 1  1  1  1  1]
 [ 1  1 27  1  9]
 [ 8  3  0  1  3]]

Is it equivalent to 'np.power(A, B)'? 
 True ----Returned by 'np.array_equal(A ** B, np.power(A, B))'


### 2.2 Matrix mainpulation
#### 2.2.1 Transpose

In [15]:
# Initialize an array(matrix)
A = np.random.randint(10, size=(3, 5))
print("A: \n", A)

# Transpose of the array
print("\nA.T: \n", A.T)

A: 
 [[6 8 6 6 0]
 [7 7 9 8 5]
 [9 7 2 9 1]]

A.T: 
 [[6 7 9]
 [8 7 7]
 [6 9 2]
 [6 8 9]
 [0 5 1]]


#### 2.2.2 Matrix Multiplication

In [16]:
# Initialize two arrays (matrices)
A = np.random.randint(10, size=(3, 5))
B = np.random.randint(10, size=(3, 5))

print("A: \n", A, "\nB: \n", B, "\nB.T: \n", B.T)

# Dot product of two arrays
print("\nA.dot(B.T): \n", A.dot(B.T))
print("\nIs it equivalent to 'np.matmul(A, B.T)'? \n", \
    np.array_equal(A.dot(B.T), np.matmul(A, B.T)),\
        "----Returned by 'np.array_equal(A.dot(B.T), np.matmul(A, B.T))'")
print("\nIs it equivalent to 'A @ B.T)'? \n", \
    np.array_equal(A.dot(B.T), A @ B.T),\
        "----Returned by 'np.array_equal(A.dot(B.T), A @ B.T)'")


A: 
 [[6 0 8 5 3]
 [7 3 2 5 5]
 [0 3 8 8 0]] 
B: 
 [[2 0 9 3 7]
 [9 2 9 4 1]
 [1 2 7 1 8]] 
B.T: 
 [[2 9 1]
 [0 2 2]
 [9 9 7]
 [3 4 1]
 [7 1 8]]

A.dot(B.T): 
 [[120 149  91]
 [ 82 112  72]
 [ 96 110  70]]

Is it equivalent to 'np.matmul(A, B.T)'? 
 True ----Returned by 'np.array_equal(A.dot(B.T), np.matmul(A, B.T))'

Is it equivalent to 'A @ B.T)'? 
 True ----Returned by 'np.array_equal(A.dot(B.T), A @ B.T)'


#### 2.2.3 Common Linear Algebra Calculation

In [17]:
# Initialize an array(matrix)
A = np.random.randint(10, size=(3, 3))
print("A: \n", A)

# Inverse of the array
print("\nnp.linalg.inv(A): \n", np.linalg.inv(A))
# Determinant of the array
print("\nnp.linalg.det(A): \n", np.linalg.det(A))
# Rank of the array
print("\nnp.linalg.matrix_rank(A): \n", np.linalg.matrix_rank(A))
# Eigenvalues of the array
print("\nnp.linalg.eig(A): \n", np.linalg.eig(A))
# Singular value decomposition of the array
print("\nnp.linalg.svd(A): \n", np.linalg.svd(A))

A: 
 [[7 2 0]
 [4 6 9]
 [5 1 9]]

np.linalg.inv(A): 
 [[ 0.13513514 -0.05405405  0.05405405]
 [ 0.02702703  0.18918919 -0.18918919]
 [-0.07807808  0.00900901  0.1021021 ]]

np.linalg.det(A): 
 333.0

np.linalg.matrix_rank(A): 
 3

np.linalg.eig(A): 
 (array([13.10160333+0.j      ,  4.44919834+2.370943j,
        4.44919834-2.370943j]), array([[-0.26574567+0.j        , -0.34105787-0.31700966j,
        -0.34105787+0.31700966j],
       [-0.81073734+0.j        ,  0.81079142+0.j        ,
         0.81079142-0.j        ],
       [-0.52161692+0.j        ,  0.01187276+0.35448654j,
         0.01187276-0.35448654j]]))

np.linalg.svd(A): 
 (array([[-0.27511584,  0.96043808, -0.04324323],
       [-0.71872393, -0.23533486, -0.65425791],
       [-0.63855085, -0.14891677,  0.75503418]]), array([15.60049953,  6.1206185 ,  3.4874695 ]), array([[-0.51238493, -0.352625  , -0.78301807],
       [ 0.82297945,  0.05880945, -0.56501882],
       [ 0.24528862, -0.93391491,  0.26007005]]))
