# Array Math

In [ ]:
import numpy as np

## 1. Basics
### 1.1 Manipulation on elements
#### 1.1.1 Modification at some certain location

In [ ]:
# Initialize an array(matrices)
A = np.arange(15).reshape(3, 5)
print("the array is A = np.arange(15).\
    reshape(3, 5): \n", A, "shape: ", A.shape)

# Modify the array at row i and column j
A[1, 3] = 100
print("\nthe modified array at [1,3] is 100: \n", A, "shape: ", A.shape)

# Modify the array at row i
A[1, :] = ([1, 2, 3, 4, 5])
print("\nthe modified array at row 1 is [1,2,3,4,5]: \n", A, "shape: ", A.shape)

# Modify at region [i:k, j:l]
A[1:3, 2:5] = 0
print("\nthe modified array at region [1:3, 2:5] is 0: \n", A, "shape: ", A.shape)


#### 1.1.2 Add or Substract

In [ ]:
print("A: \n", A)
# Add 1 to each element of the array
A = A + 1
print("\nA = A + 1: \n", A)
A = np.add(A, 1)
print("\nA = np.add(A, 1): \n", A)
print("A+1 is equivalent to np.add(A, 1)")

# Subtract 1 from each element of the array
A = A - 1
print("\nA = A - 1: \n", A)
A = np.subtract(A, 1)
print("\nA = np.subtract(A, 1): \n", A)
print("A-1 is equivalent to np.subtract(A, 1)")

#### 1.1.3 Multiply, Divide, Power and Square-root

In [ ]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("\nA: \n", A)
# Multiply each element of the array by 2
A = A * 2
print("\nA = A * 2: \n", A)
A = (np.multiply(A, 2)).astype(int)
print("\nA = np.multiply(A, 2): \n", A)
print("A*2 is equivalent to np.multiply(A, 2)")

# Divide each element of the array by 2
A = A / 2
print("\nA = A / 2: \n", A)
A = (np.divide(A, 2))
print("\nA = np.divide(A, 2): \n", A)
print("A/2 is equivalent to np.divide(A, 2)")

#### 1.1.4 Power and Square-root

In [ ]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Power each element of the array by 2
A = A ** 2
print("\nA = A ** 2: \n", A)
A = np.power(A, 2).astype(int)
print("\nA = np.power(A, 2).astype(int): \n", A)
print("A**2 is equivalent to np.power(A, 2)")

# Square root of each element of the array
A = A ** 0.5
print("\nA = A ** 0.5: \n", A)
A = np.sqrt(A)
print("\nA = np.sqrt(A): \n", A)
print("A**0.5 is equivalent to np.sqrt(A)")

#### 1.1.5 Floor, Ceil and Round

In [ ]:
# Reinitalize the array randomly with float numbers 3x5
A = np.random.rand(3, 5)
print("\nA: \n", A)

# Round each element of the array
print("\nA = np.round(A): \n", np.round(A))
# Ceil each element of the array
print("\nA = np.ceil(A): \n", np.ceil(A))
# Floor each element of the array
print("\nA = np.floor(A): \n", np.floor(A))


- Special

In [ ]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Absolute value of each element of the array
print("\nA = np.abs(A): \n", np.abs(A))
# Sine of each element of the array
print("\nA = np.sin(A):\n(cos and tan is als\
      o available) \n", np.sin(A))
# Exponential of each element of the array
print("\nA = np.exp(A): \n", np.exp(A))
# Natural logarithm of each element of the array
print("\nA = np.log(A): \n", np.log(A))

### 1.2 Statistics on Array
#### 1.2.1 Mean and Sum

In [ ]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)
# Sum of all elements of the array
print("\nnp.sum(A): \n", np.sum(A))
# Sum of all elements of the array along the column
print("\nnp.sum(A, axis=0): \n", np.sum(A, axis=0))

# Mean of all elements of the array
print("\nnp.mean(A): \n", np.mean(A))
# Mean of all elements of the array along the row
print("\nnp.mean(A, axis=1): \n", np.mean(A, axis=1))

#### 1.2.2 Sorting

In [ ]:
# Reinitalize the array
A = np.random.randint(20, size=(3, 5))
print("A: \n", A)

# Sort the array
print("\nnp.sort(A): \n", np.sort(A))
print("\nnp.sort(A, axis=1): \n", np.sort(A, axis=1))
print("\nthe default is sorting the last axis\n\
    , which is axis=1. It sorts column while row does not change")

# While in C++ we can std::sort with a functor, but python does not support it

#### 1.2.3 Min and Max

In [ ]:
# Reinitalize the array
A = np.arange(15).reshape(3, 5)
print("A: \n", A)

# Minimum of all elements of the array
print("\nnp.min(A): \n", np.min(A))
# Minimum of all elements of the array along the row
print("\nnp.min(A, axis=1): \n", np.min(A, axis=1))

# Maximum of all elements of the array
print("\nnp.max(A): \n", np.max(A))
# Maximum of all elements of the array along the column
print("\nnp.max(A, axis=0): \n", np.max(A, axis=0))

#### 1.2.4 Variance, Covariance, Standard Deviation

In [ ]:
# Reinitalize the array
A = (np.random.rand(3,5)*100).astype(int)
print("A: \n", A)

# Variance of all elements of the array
print("\nnp.var(A): \n", np.var(A))
# Variance of all elements of the array along the row
print("\nnp.var(A, axis=1): \n", np.var(A, axis=1))

# Standard deviation of all elements of the array
print("\nnp.std(A): \n", np.std(A))
# Standard deviation of all elements of the array along the column
print("\nnp.std(A, axis=0): \n", np.std(A, axis=0))

# Correlation coefficient of all elements of the array
print("\nnp.corrcoef(A): \n", np.corrcoef(A))


## 2. Linear Algebra
### 2.1 Elementwise manipulations
#### 2.2.1 Addition and Subatraction

In [25]:
# Initialize two arrays (matrices)
A = np.random.randint(10, size=(3, 5))
B = np.random.randint(10, size=(3, 5))

print("A: \n", A, "\nB: \n", B)

# Element-wise addition of two arrays
print("\nA + B: \n", A + B)
print("\nIs it' equivalent to 'np.add(A, B)'? \n", \
    np.array_equal(A + B, np.add(A, B)),\
        "----Returned by 'np.array_equal(A + B, np.add(A, B))'")

# Element-wise subtraction of two arrays
print("\nA - B: \n", A - B)
print("\nIs it equivalent to 'np.subtract(A, B)'? \n", \
    np.array_equal(A - B, np.subtract(A, B)),\
        "----Returned by 'np.array_equal(A - B, np.subtract(A, B))'")


A: 
 [[7 4 8 1 3]
 [4 1 6 6 3]
 [6 8 4 5 8]] 
B: 
 [[5 7 7 0 5]
 [6 8 6 0 2]
 [5 5 4 2 5]]

A + B: 
 [[12 11 15  1  8]
 [10  9 12  6  5]
 [11 13  8  7 13]]

Is it' equivalent to 'np.add(A, B)'? 
 True ----Returned by 'np.array_equal(A + B, np.add(A, B))'

A - B: 
 [[ 2 -3  1  1 -2]
 [-2 -7  0  6  1]
 [ 1  3  0  3  3]]

Is it equivalent to 'np.subtract(A, B)'? 
 True ----Returned by 'np.array_equal(A - B, np.subtract(A, B))'


#### 2.2.2 Multiplication and Division

In [26]:
# Reinitialize two arrays (matrices)
A = np.random.randint(10, size=(3, 5))
B = np.random.randint(10, size=(3, 5))

print("A: \n", A, "\nB: \n", B)

# Elementwise multiplication of two arrays
print("\nA * B: \n", A * B)
print("\nIs it equivalent to 'np.multiply(A, B)'? \n", \
    np.array_equal(A * B, np.multiply(A, B)),\
        "----Returned by 'np.array_equal(A * B, np.multiply(A, B))'")

# Elementwise division of two arrays
print("\nA / B: \n", A / B)
print("\nIs it equivalent to 'np.divide(A, B)'? \n", \
    np.array_equal(A / B, np.divide(A, B)),\
        "----Returned by 'np.array_equal(A / B, np.divide(A, B))'")

A: 
 [[8 8 4 2 7]
 [5 9 7 9 4]
 [1 2 3 7 4]] 
B: 
 [[5 4 2 4 1]
 [2 8 5 4 9]
 [1 8 8 9 1]]

A * B: 
 [[40 32  8  8  7]
 [10 72 35 36 36]
 [ 1 16 24 63  4]]

Is it equivalent to 'np.multiply(A, B)'? 
 True ----Returned by 'np.array_equal(A * B, np.multiply(A, B))'

A / B: 
 [[1.6        2.         2.         0.5        7.        ]
 [2.5        1.125      1.4        2.25       0.44444444]
 [1.         0.25       0.375      0.77777778 4.        ]]

Is it equivalent to 'np.divide(A, B)'? 
 True ----Returned by 'np.array_equal(A / B, np.divide(A, B))'


#### 2.2.3 Elementwise Power

In [ ]:
# Reinitialize two arrays (matrices)